[tool.poetry]
name = "Vivawest_scraper"
version = "0.1.0"
description = ""
authors = ["floriankretschmer <entepotenz@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
selenium = "4.39.0"
requests = "2.32.5"

[tool.poetry.group.dev.dependencies]
black = "25.12.0"
yapf = "0.43.0"
toml = "0.10.2"
mypy = "1.19.1"
flake8 = "7.3.0"
ruff = "0.14.10"
types-requests = "2.32.4.20250913"
pre-commit = "4.5.1"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
